# Specify the build worker image with Visual Studio 2022
image: Visual Studio 2022

# Set environment variables
environment:
  VULKAN_SDK_VERSION: '1.3.261.1'
  VULKAN_SDK: 'C:\\VulkanSDK\\$(VULKAN_SDK_VERSION)'
  VK_SDK_PATH: 'C:\\VulkanSDK\\$(VULKAN_SDK_VERSION)'

# Cache the Vulkan SDK installer and vcpkg installed packages to speed up subsequent builds
cache:
  - C:\\VulkanSDK\\Installer
  - C:\\tools\\vcpkg\\installed

# Install section to download and install Vulkan SDK and other dependencies
install:
  # Download the Vulkan SDK installer
  - ps: |
      $VulkanSdkInstaller = 'VulkanSDK.exe'
      $installerPath = "C:\\VulkanSDK\\Installer\\$VulkanSdkInstaller"
      if (-Not (Test-Path $installerPath)) {
        Write-Output "Downloading Vulkan SDK Installer..."
        Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/download/$env:VULKAN_SDK_VERSION/windows/VulkanSDK-$env:VULKAN_SDK_VERSION-Installer.exe" -OutFile $installerPath
      } else {
        Write-Output "Using cached Vulkan SDK Installer."
      }
  # Install the Vulkan SDK silently
  - ps: |
      Start-Process -FilePath $installerPath -ArgumentList '--accept-licenses', '--default-answer', '--confirm-command', 'install' -NoNewWindow -Wait
  # Update the PATH environment variable
  - ps: |
      $env:PATH = "$env:VULKAN_SDK\Bin;$env:PATH"
      [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH, [System.EnvironmentVariableTarget]::Process)
  # Ensure vcpkg is up-to-date and install necessary packages
  - ps: |
      if (-Not (Test-Path 'C:\tools\vcpkg')) {
        git clone https://github.com/microsoft/vcpkg.git C:\tools\vcpkg
        & C:\tools\vcpkg\bootstrap-vcpkg.bat
      } else {
        cd C:\tools\vcpkg
        Write-Output "Updating vcpkg..."
        git pull > $null 2>&1
        & .\bootstrap-vcpkg.bat > $null 2>&1
      }
      Write-Output "Installing required vcpkg packages..."
      & C:\tools\vcpkg\vcpkg.exe integrate install > $null 2>&1
      & C:\tools\vcpkg\vcpkg.exe install glfw3 glm > $null 2>&1

# Build script
build_script:
  - ps: |
      # Use vswhere to locate MSBuild dynamically
      $vswherePath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
      if (-Not (Test-Path $vswherePath)) {
        Write-Error "vswhere.exe not found at $vswherePath"
        exit 1
      }
      $msbuildPath = & $vswherePath -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
      if (-Not (Test-Path $msbuildPath)) {
        Write-Error "MSBuild.exe not found."
        exit 1
      }
      Write-Output "Found MSBuild at $msbuildPath"
      
      $solutionPath = 'C:\projects\vesper\Vesper.sln'

      # Validate the solution configuration
      Write-Output "Validating solution configuration..."
      & $msbuildPath $solutionPath /t:ValidateSolutionConfiguration > build_validation_log.txt 2>&1
      if ($LastExitCode -ne 0) {
        Write-Error "Solution validation failed. Check build_validation_log.txt for details."
        exit 1
      }

      # Build the solution
      Write-Output "Building the solution..."
      $msbuildArgs = '/p:Configuration=Release /p:Platform=x64'
      & $msbuildPath $solutionPath $msbuildArgs > build_log.txt 2>&1
      if ($LastExitCode -ne 0) {
        Write-Error "Build failed. Check build_log.txt for details."
        exit 1
      }
      Write-Output "Build completed successfully."
