# Specify the build worker image with Visual Studio 2022
image: Visual Studio 2022

# Set environment variables
environment:
  VULKAN_SDK_VERSION: '1.3.261.1'
  VULKAN_SDK: 'C:\VulkanSDK\$(VULKAN_SDK_VERSION)'

# Install section to download and install Vulkan SDK
install:
  # Download the Vulkan SDK installer
  - ps: |
      $VulkanSdkInstaller = 'VulkanSDK.exe'
      Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/download/$env:VULKAN_SDK_VERSION/windows/VulkanSDK-$env:VULKAN_SDK_VERSION-Installer.exe" -OutFile $VulkanSdkInstaller
  # Install the Vulkan SDK silently
  - ps: |
      Start-Process -FilePath .\$VulkanSdkInstaller -ArgumentList '--accept-licenses', '--default-answer', '--confirm-command', 'install' -NoNewWindow -Wait
  # Update the PATH environment variable
  - ps: |
      $env:PATH = "$env:VULKAN_SDK\Bin;$env:PATH"
      [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH, [System.EnvironmentVariableTarget]::Process)

# Build script
build_script:
  - ps: |
      # Navigate to the solution directory
      cd C:\projects\vesper
      # Build the solution using MSBuild
      & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" Vesper.sln /p:Configuration=Release
