version: 1.0.{build}
image: Visual Studio 2022

environment:
  matrix:
    - CONFIGURATION: Debug
      PLATFORM: x64
    - CONFIGURATION: Release
      PLATFORM: x64
  VK_SDK_VERSION: "1.3.261.1"
  VK_SDK_INSTALLER: "https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanSDK-1.3.261.1-Installer.exe"
  VK_SDK_PATH: "C:\\VulkanSDK\\1.3.261.1"

init:
  - ps: |
      if (!(Test-Path $env:VK_SDK_PATH)) {
        Write-Host "Downloading Vulkan SDK..."
        $installerPath = "$PWD\\VulkanSDK-Installer.exe"
        Invoke-WebRequest $env:VK_SDK_INSTALLER -OutFile $installerPath -Verbose

        if (!(Test-Path $installerPath)) {
          Write-Error "Failed to download Vulkan SDK installer."
          exit 1
        }

        Write-Host "Installing Vulkan SDK..."
        Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait -NoNewWindow

        if (Test-Path $installerPath) {
          Write-Host "Cleaning up installer..."
          Remove-Item $installerPath -Verbose
        }
      }
      if (!(Test-Path $env:VK_SDK_PATH)) {
        Write-Error "Vulkan SDK installation failed or path not found: $env:VK_SDK_PATH"
        exit 1
      }

build_script:
  - cmd: >
      "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe"
      Vesper.sln
      /p:Configuration=%CONFIGURATION%
      /p:Platform=%PLATFORM%

artifacts:
  - path: "**\\bin\\%CONFIGURATION%\\*"
    name: Build-%CONFIGURATION%-%PLATFORM%

test_script:
  # Include testing commands here if applicable.
  # Example: Run unit tests or validation scripts.

deploy:
  # Add deployment configurations here if needed.
