name: Build and Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Configure Visual Studio
        run: |
          "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installer.exe" modify \
          --add Microsoft.VisualStudio.Component.Windows10SDK.10.0.19041 \
          Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
          --quiet --wait --norestart

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore Vesper.sln

      - name: Install Vulkan SDK and dependencies
        run: |
          choco install vulkan-sdk --version=1.3.243.0 -y
          set VULKAN_SDK=C:\\VulkanSDK\\1.3.243.0
          mkdir %VULKAN_SDK%\\Include\\glm
          mkdir %VULKAN_SDK%\\Include\\vma

      - name: Install GLM into Vulkan SDK dependencies
        run: |
          git clone https://github.com/g-truc/glm.git temp_glm
          xcopy temp_glm\\glm %VULKAN_SDK%\\Include\\glm /E /H /C /I
          rmdir /S /Q temp_glm

      - name: Install Vulkan Memory Allocator (VMA) into Vulkan SDK dependencies
        run: |
          git clone https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git temp_vma
          xcopy temp_vma\\include\\vma.h %VULKAN_SDK%\\Include\\vma /E /H /C /I
          rmdir /S /Q temp_vma

      - name: Build solution
        run: |
          msbuild Vesper.sln /p:Configuration=Release /m

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: |
            **/bin/
            **/obj/
