# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.261.1
        cache: true

    - name: Debug Vulkan SDK Installation
      run: |
        echo "Checking Vulkan SDK installation directory..."
        ls -l D:/a/Vesper/Vesper/VULKAN_SDK || echo "Installation path not found!"

    - name: Set VULKAN_SDK Environment Variable
      run: echo "VULKAN_SDK=D:/a/Vesper/Vesper/VULKAN_SDK" >> $GITHUB_ENV
    
    - name: Force Reload Environment Variables
      run: env
       
    - name: Verify VULKAN_SDK Environment Variable
      run: |
        echo "Verifying Vulkan SDK..."
        echo "VULKAN_SDK=$env:VULKAN_SDK"
        ls -l $env:VULKAN_SDK || echo "VULKAN_SDK path is incorrect!"

    - name: Debug VULKAN_SDK Variable
      run: echo "VULKAN_SDK=$env:VULKAN_SDK"

    - name: Download Vulkan Memory Allocator
      run: |
        echo "Downloading Vulkan Memory Allocator header..."
        mkdir -p $env:VULKAN_SDK/Include/vma
        curl -L https://raw.githubusercontent.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/master/include/vk_mem_alloc.h -o $env:VULKAN_SDK/Include/vma/vk_mem_alloc.h
    
    - name: Download GLM Math Library
      run: |
        echo "Cloning GLM Math Library..."
        mkdir -p $env:VULKAN_SDK/Include/glm
        git clone --depth 1 https://github.com/g-truc/glm.git temp_glm
        cp -r temp_glm/glm/* $env:VULKAN_SDK/Include/glm
        Remove-Item temp_glm -Recurse -Force
    
    - name: Verify VMA and GLM Headers in Vulkan SDK
      run: |
        echo "Checking VMA and GLM headers in Vulkan SDK..."
        ls -l $env:VULKAN_SDK/Include/vma || echo "VMA header not found!"
        ls -l $env:VULKAN_SDK/Include/glm || echo "GLM headers not found!"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Windows SDK
      run: choco install windows-sdk-10

    - name: Initialize MSVC Environment
      shell: cmd
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:IncludePath="${{env.VULKAN_SDK}}/Include" /p:LibraryPath="${{env.VULKAN_SDK}}/Lib" ${{env.SOLUTION_FILE_PATH}}
